import {
	MessagesConversation,
	UsersUserFull,
} from "vk-io/lib/api/schemas/objects";
import { user } from "./VK/core";

export async function getUserData(user_id: number): Promise<UsersUserFull> {
	return (
		await user.getVK().api.users.get({
			user_id: user_id,
			fields: [
				"first_name_nom",
				"first_name_gen",
				"first_name_dat",
				"first_name_acc",
				"first_name_ins",
				"first_name_abl",
				"last_name_nom",
				"last_name_gen",
				"last_name_dat",
				"last_name_acc",
				"last_name_ins",
				"last_name_abl",
				"photo_id",
				"verified",
				"sex",
				"bdate",
				"city",
				"country",
				"home_town",
				"has_photo",
				"photo_50",
				"photo_100",
				"photo_200_orig",
				"photo_200",
				"photo_400",
				"photo_400_orig",
				"photo_max",
				"photo_max_orig",
				"photo_max_size",
				"online",
				"lists",
				"domain",
				"has_mobile",
				"contacts",
				"site",
				"education",
				"universities",
				"schools",
				"status",
				"last_seen",
				"followers_count",
				"counters",
				"common_count",
				"occupation",
				"nickname",
				"relatives",
				"relation",
				"personal",
				"connections",
				"exports",
				"wall_comments",
				"activities",
				"interests",
				"music",
				"movies",
				"tv",
				"books",
				"games",
				"about",
				"quotes",
				"can_post",
				"can_see_all_posts",
				"can_see_audio",
				"can_write_private_message",
				"can_send_friend_request",
				"is_favorite",
				"is_hidden_from_feed",
				"timezone",
				"screen_name",
				"maiden_name",
				"crop_photo",
				"is_friend",
				"friend_status",
				"career",
				"military",
				"blacklisted",
				"blacklisted_by_me",
				"can_subscribe_posts",
				"descriptions",
				"trending",
				"mutual",
				"friendship_weeks",
				"can_invite_to_chats",
				"stories_archive_count",
				"video_live_level",
				"video_live_count",
				"clips_count",
				"service_description",
				"is_dead",
			],
		})
	)[0];
}

export async function getChatData(
	chat_id: number,
): Promise<MessagesConversation> {
	return (
		await user.getVK().api.messages.getConversationsById({
			peer_ids: 2e9 + chat_id,
			extended: 1,
			fields: [
				"about",
				"action_button",
				"activities",
				"activity",
				"addresses",
				"admin_level",
				"age_limits",
				"author_id",
				"ban_info",
				"bdate",
				"blacklisted",
				"blacklisted_by_me",
				"books",
				"can_create_topic",
				"can_message",
				"can_post",
				"can_see_all_posts",
				"can_see_audio",
				"can_send_friend_request",
				"can_upload_video",
				"can_write_private_message",
				"career",
				"city",
				"common_count",
				"connections",
				"contacts",
				"counters",
				"country",
				"cover",
				"crop_photo",
				"deactivated",
				"description",
				"domain",
				"education",
				"exports",
				"finish_date",
				"fixed_post",
				"followers_count",
				"friend_status",
				"games",
				"has_market_app",
				"has_mobile",
				"has_photo",
				"home_town",
				"id",
				"interests",
				"is_admin",
				"is_closed",
				"is_favorite",
				"is_friend",
				"is_hidden_from_feed",
				"is_member",
				"is_messages_blocked",
				"can_send_notify",
				"is_subscribed",
				"last_seen",
				"links",
				"lists",
				"maiden_name",
				"main_album_id",
				"main_section",
				"market",
				"member_status",
				"members_count",
				"military",
				"movies",
				"music",
				"name",
				"nickname",
				"occupation",
				"online",
				"online_status",
				"personal",
				"phone",
				"photo_100",
				"photo_200",
				"photo_200_orig",
				"photo_400_orig",
				"photo_50",
				"photo_id",
				"photo_max",
				"photo_max_orig",
				"quotes",
				"relation",
				"relatives",
				"schools",
				"screen_name",
				"sex",
				"site",
				"start_date",
				"status",
				"timezone",
				"trending",
				"tv",
				"type",
				"universities",
				"verified",
				"wall_comments",
				"wiki_page",
				"vk_admin_status",
			],
		})
	)[0];
}

export function generateRandomString(length: number): string {
	let output = "";
	const words = "defbca1234567890";
	while (output.length < length) {
		output += words[Math.floor(Math.random() * words.length)];
	}
	return output;
}
